theme: jekyll-theme-cayman
title: Beyond Graph Mining - Higher-Order Data Analytics for Temporal Network Data
description: Companion website for KDD'18 Hands-On Tutorial on Higher-Order Data Analytics for Temporal Network Data