theme: jekyll-theme-cayman
title: Infomap Notebooks - Hands-on Tutorials on Higher-Order Data Analytics
description: Jupyter notebooks with tutorials on using Infomap to analyse higher-order network data